services:
  db:
    image: mysql:8.0.33-debian
    container_name: guestsapp-db
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: guest_tracker
      MYSQL_TCP_PORT: 3308
    expose: [ 3308 ]
    networks: [ guestsapp-network ]

  guestsapp:
    image: guestsapp
    container_name: guestsapp
    depends_on: [ db ]
    restart: on-failure
    build: .
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/guest_tracker?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: ${PASSWORD}
      SERVER.PORT: 80
      USERS.PASSWORD: ${USERS_PASSWORD}
    ports: [ 8081:80 ]
    networks: [ guestsapp-network ]

networks:
  guestsapp-network:
    driver: bridge
